/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class AAndConjunction extends PConjunction
{
    private PConjunction _conjunction_;
    private TTAnd _tAnd_;
    private PBody _body_;

    public AAndConjunction()
    {
    }

    public AAndConjunction(
        PConjunction _conjunction_,
        TTAnd _tAnd_,
        PBody _body_)
    {
        setConjunction(_conjunction_);

        setTAnd(_tAnd_);

        setBody(_body_);

    }
    public Object clone()
    {
        return new AAndConjunction(
            (PConjunction) cloneNode(_conjunction_),
            (TTAnd) cloneNode(_tAnd_),
            (PBody) cloneNode(_body_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndConjunction(this);
    }

    public PConjunction getConjunction()
    {
        return _conjunction_;
    }

    public void setConjunction(PConjunction node)
    {
        if(_conjunction_ != null)
        {
            _conjunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _conjunction_ = node;
    }

    public TTAnd getTAnd()
    {
        return _tAnd_;
    }

    public void setTAnd(TTAnd node)
    {
        if(_tAnd_ != null)
        {
            _tAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tAnd_ = node;
    }

    public PBody getBody()
    {
        return _body_;
    }

    public void setBody(PBody node)
    {
        if(_body_ != null)
        {
            _body_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _body_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_conjunction_)
            + toString(_tAnd_)
            + toString(_body_);
    }

    void removeChild(Node child)
    {
        if(_conjunction_ == child)
        {
            _conjunction_ = null;
            return;
        }

        if(_tAnd_ == child)
        {
            _tAnd_ = null;
            return;
        }

        if(_body_ == child)
        {
            _body_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_conjunction_ == oldChild)
        {
            setConjunction((PConjunction) newChild);
            return;
        }

        if(_tAnd_ == oldChild)
        {
            setTAnd((TTAnd) newChild);
            return;
        }

        if(_body_ == oldChild)
        {
            setBody((PBody) newChild);
            return;
        }

    }
}
