/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ABody extends PBody
{
    private PPredicate _predicate_;

    public ABody()
    {
    }

    public ABody(
        PPredicate _predicate_)
    {
        setPredicate(_predicate_);

    }
    public Object clone()
    {
        return new ABody(
            (PPredicate) cloneNode(_predicate_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABody(this);
    }

    public PPredicate getPredicate()
    {
        return _predicate_;
    }

    public void setPredicate(PPredicate node)
    {
        if(_predicate_ != null)
        {
            _predicate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _predicate_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_predicate_);
    }

    void removeChild(Node child)
    {
        if(_predicate_ == child)
        {
            _predicate_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_predicate_ == oldChild)
        {
            setPredicate((PPredicate) newChild);
            return;
        }

    }
}
