/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ABodyConjunction extends PConjunction
{
    private PBody _body_;

    public ABodyConjunction()
    {
    }

    public ABodyConjunction(
        PBody _body_)
    {
        setBody(_body_);

    }
    public Object clone()
    {
        return new ABodyConjunction(
            (PBody) cloneNode(_body_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABodyConjunction(this);
    }

    public PBody getBody()
    {
        return _body_;
    }

    public void setBody(PBody node)
    {
        if(_body_ != null)
        {
            _body_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _body_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_body_);
    }

    void removeChild(Node child)
    {
        if(_body_ == child)
        {
            _body_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_body_ == oldChild)
        {
            setBody((PBody) newChild);
            return;
        }

    }
}
