/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ACommaConjunction extends PConjunction
{
    private PConjunction _conjunction_;
    private TTComma _tComma_;
    private PBody _body_;

    public ACommaConjunction()
    {
    }

    public ACommaConjunction(
        PConjunction _conjunction_,
        TTComma _tComma_,
        PBody _body_)
    {
        setConjunction(_conjunction_);

        setTComma(_tComma_);

        setBody(_body_);

    }
    public Object clone()
    {
        return new ACommaConjunction(
            (PConjunction) cloneNode(_conjunction_),
            (TTComma) cloneNode(_tComma_),
            (PBody) cloneNode(_body_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaConjunction(this);
    }

    public PConjunction getConjunction()
    {
        return _conjunction_;
    }

    public void setConjunction(PConjunction node)
    {
        if(_conjunction_ != null)
        {
            _conjunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _conjunction_ = node;
    }

    public TTComma getTComma()
    {
        return _tComma_;
    }

    public void setTComma(TTComma node)
    {
        if(_tComma_ != null)
        {
            _tComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tComma_ = node;
    }

    public PBody getBody()
    {
        return _body_;
    }

    public void setBody(PBody node)
    {
        if(_body_ != null)
        {
            _body_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _body_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_conjunction_)
            + toString(_tComma_)
            + toString(_body_);
    }

    void removeChild(Node child)
    {
        if(_conjunction_ == child)
        {
            _conjunction_ = null;
            return;
        }

        if(_tComma_ == child)
        {
            _tComma_ = null;
            return;
        }

        if(_body_ == child)
        {
            _body_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_conjunction_ == oldChild)
        {
            setConjunction((PConjunction) newChild);
            return;
        }

        if(_tComma_ == oldChild)
        {
            setTComma((TTComma) newChild);
            return;
        }

        if(_body_ == oldChild)
        {
            setBody((PBody) newChild);
            return;
        }

    }
}
