/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AEqvarBuiltin extends PBuiltin
{
    private TTVariable _first_;
    private TTEq _tEq_;
    private TTVariable _second_;

    public AEqvarBuiltin()
    {
        // Constructor
    }

    public AEqvarBuiltin(
        @SuppressWarnings("hiding") TTVariable _first_,
        @SuppressWarnings("hiding") TTEq _tEq_,
        @SuppressWarnings("hiding") TTVariable _second_)
    {
        // Constructor
        setFirst(_first_);

        setTEq(_tEq_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new AEqvarBuiltin(
            cloneNode(this._first_),
            cloneNode(this._tEq_),
            cloneNode(this._second_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqvarBuiltin(this);
    }

    public TTVariable getFirst()
    {
        return this._first_;
    }

    public void setFirst(TTVariable node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TTEq getTEq()
    {
        return this._tEq_;
    }

    public void setTEq(TTEq node)
    {
        if(this._tEq_ != null)
        {
            this._tEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tEq_ = node;
    }

    public TTVariable getSecond()
    {
        return this._second_;
    }

    public void setSecond(TTVariable node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._tEq_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._tEq_ == child)
        {
            this._tEq_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((TTVariable) newChild);
            return;
        }

        if(this._tEq_ == oldChild)
        {
            setTEq((TTEq) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((TTVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
