/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class AFactExpr extends PExpr
{
    private PPredicate _predicate_;
    private TTDot _tDot_;

    public AFactExpr()
    {
    }

    public AFactExpr(
        PPredicate _predicate_,
        TTDot _tDot_)
    {
        setPredicate(_predicate_);

        setTDot(_tDot_);

    }
    public Object clone()
    {
        return new AFactExpr(
            (PPredicate) cloneNode(_predicate_),
            (TTDot) cloneNode(_tDot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFactExpr(this);
    }

    public PPredicate getPredicate()
    {
        return _predicate_;
    }

    public void setPredicate(PPredicate node)
    {
        if(_predicate_ != null)
        {
            _predicate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _predicate_ = node;
    }

    public TTDot getTDot()
    {
        return _tDot_;
    }

    public void setTDot(TTDot node)
    {
        if(_tDot_ != null)
        {
            _tDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tDot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_predicate_)
            + toString(_tDot_);
    }

    void removeChild(Node child)
    {
        if(_predicate_ == child)
        {
            _predicate_ = null;
            return;
        }

        if(_tDot_ == child)
        {
            _tDot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_predicate_ == oldChild)
        {
            setPredicate((PPredicate) newChild);
            return;
        }

        if(_tDot_ == oldChild)
        {
            setTDot((TTDot) newChild);
            return;
        }

    }
}
