/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ANegatedBody extends PBody
{
    private TTNot _tNot_;
    private PPredicate _predicate_;

    public ANegatedBody()
    {
    }

    public ANegatedBody(
        TTNot _tNot_,
        PPredicate _predicate_)
    {
        setTNot(_tNot_);

        setPredicate(_predicate_);

    }
    public Object clone()
    {
        return new ANegatedBody(
            (TTNot) cloneNode(_tNot_),
            (PPredicate) cloneNode(_predicate_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegatedBody(this);
    }

    public TTNot getTNot()
    {
        return _tNot_;
    }

    public void setTNot(TTNot node)
    {
        if(_tNot_ != null)
        {
            _tNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tNot_ = node;
    }

    public PPredicate getPredicate()
    {
        return _predicate_;
    }

    public void setPredicate(PPredicate node)
    {
        if(_predicate_ != null)
        {
            _predicate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _predicate_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tNot_)
            + toString(_predicate_);
    }

    void removeChild(Node child)
    {
        if(_tNot_ == child)
        {
            _tNot_ = null;
            return;
        }

        if(_predicate_ == child)
        {
            _predicate_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tNot_ == oldChild)
        {
            setTNot((TTNot) newChild);
            return;
        }

        if(_predicate_ == oldChild)
        {
            setPredicate((PPredicate) newChild);
            return;
        }

    }
}
