/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANeqvarBuiltin extends PBuiltin
{
    private TTVariable _first_;
    private TTNeq _tNeq_;
    private TTVariable _second_;

    public ANeqvarBuiltin()
    {
        // Constructor
    }

    public ANeqvarBuiltin(
        @SuppressWarnings("hiding") TTVariable _first_,
        @SuppressWarnings("hiding") TTNeq _tNeq_,
        @SuppressWarnings("hiding") TTVariable _second_)
    {
        // Constructor
        setFirst(_first_);

        setTNeq(_tNeq_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new ANeqvarBuiltin(
            cloneNode(this._first_),
            cloneNode(this._tNeq_),
            cloneNode(this._second_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeqvarBuiltin(this);
    }

    public TTVariable getFirst()
    {
        return this._first_;
    }

    public void setFirst(TTVariable node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TTNeq getTNeq()
    {
        return this._tNeq_;
    }

    public void setTNeq(TTNeq node)
    {
        if(this._tNeq_ != null)
        {
            this._tNeq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tNeq_ = node;
    }

    public TTVariable getSecond()
    {
        return this._second_;
    }

    public void setSecond(TTVariable node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._tNeq_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._tNeq_ == child)
        {
            this._tNeq_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((TTVariable) newChild);
            return;
        }

        if(this._tNeq_ == oldChild)
        {
            setTNeq((TTNeq) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((TTVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
