/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

@SuppressWarnings("nls")
public final class AOtraBuiltin extends PBuiltin
{
    private TTVariable _tVariable_;
    private TTEq _tEq_;
    private TTId _tId_;

    public AOtraBuiltin()
    {
        // Constructor
    }

    public AOtraBuiltin(
        @SuppressWarnings("hiding") TTVariable _tVariable_,
        @SuppressWarnings("hiding") TTEq _tEq_,
        @SuppressWarnings("hiding") TTId _tId_)
    {
        // Constructor
        setTVariable(_tVariable_);

        setTEq(_tEq_);

        setTId(_tId_);

    }

    @Override
    public Object clone()
    {
        return new AOtraBuiltin(
            cloneNode(this._tVariable_),
            cloneNode(this._tEq_),
            cloneNode(this._tId_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOtraBuiltin(this);
    }

    public TTVariable getTVariable()
    {
        return this._tVariable_;
    }

    public void setTVariable(TTVariable node)
    {
        if(this._tVariable_ != null)
        {
            this._tVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tVariable_ = node;
    }

    public TTEq getTEq()
    {
        return this._tEq_;
    }

    public void setTEq(TTEq node)
    {
        if(this._tEq_ != null)
        {
            this._tEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tEq_ = node;
    }

    public TTId getTId()
    {
        return this._tId_;
    }

    public void setTId(TTId node)
    {
        if(this._tId_ != null)
        {
            this._tId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tVariable_)
            + toString(this._tEq_)
            + toString(this._tId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tVariable_ == child)
        {
            this._tVariable_ = null;
            return;
        }

        if(this._tEq_ == child)
        {
            this._tEq_ = null;
            return;
        }

        if(this._tId_ == child)
        {
            this._tId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tVariable_ == oldChild)
        {
            setTVariable((TTVariable) newChild);
            return;
        }

        if(this._tEq_ == oldChild)
        {
            setTEq((TTEq) newChild);
            return;
        }

        if(this._tId_ == oldChild)
        {
            setTId((TTId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
