/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class AParamlist extends PParamlist
{
    private TTLpar _tLpar_;
    private PTermlist _termlist_;
    private TTRpar _tRpar_;

    public AParamlist()
    {
    }

    public AParamlist(
        TTLpar _tLpar_,
        PTermlist _termlist_,
        TTRpar _tRpar_)
    {
        setTLpar(_tLpar_);

        setTermlist(_termlist_);

        setTRpar(_tRpar_);

    }
    public Object clone()
    {
        return new AParamlist(
            (TTLpar) cloneNode(_tLpar_),
            (PTermlist) cloneNode(_termlist_),
            (TTRpar) cloneNode(_tRpar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamlist(this);
    }

    public TTLpar getTLpar()
    {
        return _tLpar_;
    }

    public void setTLpar(TTLpar node)
    {
        if(_tLpar_ != null)
        {
            _tLpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tLpar_ = node;
    }

    public PTermlist getTermlist()
    {
        return _termlist_;
    }

    public void setTermlist(PTermlist node)
    {
        if(_termlist_ != null)
        {
            _termlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termlist_ = node;
    }

    public TTRpar getTRpar()
    {
        return _tRpar_;
    }

    public void setTRpar(TTRpar node)
    {
        if(_tRpar_ != null)
        {
            _tRpar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tRpar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tLpar_)
            + toString(_termlist_)
            + toString(_tRpar_);
    }

    void removeChild(Node child)
    {
        if(_tLpar_ == child)
        {
            _tLpar_ = null;
            return;
        }

        if(_termlist_ == child)
        {
            _termlist_ = null;
            return;
        }

        if(_tRpar_ == child)
        {
            _tRpar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tLpar_ == oldChild)
        {
            setTLpar((TTLpar) newChild);
            return;
        }

        if(_termlist_ == oldChild)
        {
            setTermlist((PTermlist) newChild);
            return;
        }

        if(_tRpar_ == oldChild)
        {
            setTRpar((TTRpar) newChild);
            return;
        }

    }
}
