/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class AProgram extends PProgram
{
    private final LinkedList _expr_ = new TypedLinkedList(new Expr_Cast());

    public AProgram()
    {
    }

    public AProgram(
        List _expr_)
    {
        {
            this._expr_.clear();
            this._expr_.addAll(_expr_);
        }

    }

    public AProgram(
        XPExpr _expr_)
    {
        if(_expr_ != null)
        {
            while(_expr_ instanceof X1PExpr)
            {
                this._expr_.addFirst(((X1PExpr) _expr_).getPExpr());
                _expr_ = ((X1PExpr) _expr_).getXPExpr();
            }
            this._expr_.addFirst(((X2PExpr) _expr_).getPExpr());
        }

    }
    public Object clone()
    {
        return new AProgram(
            cloneList(_expr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList getExpr()
    {
        return _expr_;
    }

    public void setExpr(List list)
    {
        _expr_.clear();
        _expr_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_expr_);
    }

    void removeChild(Node child)
    {
        if(_expr_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _expr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Expr_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PExpr node = (PExpr) o;

            if((node.parent() != null) &&
                (node.parent() != AProgram.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AProgram.this))
            {
                node.parent(AProgram.this);
            }

            return node;
        }
    }
}
