/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class AQueryExpr extends PExpr
{
    private TTQuery _tQuery_;
    private PConjunction _conjunction_;
    private TTDot _tDot_;

    public AQueryExpr()
    {
    }

    public AQueryExpr(
        TTQuery _tQuery_,
        PConjunction _conjunction_,
        TTDot _tDot_)
    {
        setTQuery(_tQuery_);

        setConjunction(_conjunction_);

        setTDot(_tDot_);

    }
    public Object clone()
    {
        return new AQueryExpr(
            (TTQuery) cloneNode(_tQuery_),
            (PConjunction) cloneNode(_conjunction_),
            (TTDot) cloneNode(_tDot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQueryExpr(this);
    }

    public TTQuery getTQuery()
    {
        return _tQuery_;
    }

    public void setTQuery(TTQuery node)
    {
        if(_tQuery_ != null)
        {
            _tQuery_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tQuery_ = node;
    }

    public PConjunction getConjunction()
    {
        return _conjunction_;
    }

    public void setConjunction(PConjunction node)
    {
        if(_conjunction_ != null)
        {
            _conjunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _conjunction_ = node;
    }

    public TTDot getTDot()
    {
        return _tDot_;
    }

    public void setTDot(TTDot node)
    {
        if(_tDot_ != null)
        {
            _tDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tDot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tQuery_)
            + toString(_conjunction_)
            + toString(_tDot_);
    }

    void removeChild(Node child)
    {
        if(_tQuery_ == child)
        {
            _tQuery_ = null;
            return;
        }

        if(_conjunction_ == child)
        {
            _conjunction_ = null;
            return;
        }

        if(_tDot_ == child)
        {
            _tDot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tQuery_ == oldChild)
        {
            setTQuery((TTQuery) newChild);
            return;
        }

        if(_conjunction_ == oldChild)
        {
            setConjunction((PConjunction) newChild);
            return;
        }

        if(_tDot_ == oldChild)
        {
            setTDot((TTDot) newChild);
            return;
        }

    }
}
