/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ARuleExpr extends PExpr
{
    private PPredicate _predicate_;
    private TTImpliedby _tImpliedby_;
    private PConjunction _conjunction_;
    private TTDot _tDot_;

    public ARuleExpr()
    {
    }

    public ARuleExpr(
        PPredicate _predicate_,
        TTImpliedby _tImpliedby_,
        PConjunction _conjunction_,
        TTDot _tDot_)
    {
        setPredicate(_predicate_);

        setTImpliedby(_tImpliedby_);

        setConjunction(_conjunction_);

        setTDot(_tDot_);

    }
    public Object clone()
    {
        return new ARuleExpr(
            (PPredicate) cloneNode(_predicate_),
            (TTImpliedby) cloneNode(_tImpliedby_),
            (PConjunction) cloneNode(_conjunction_),
            (TTDot) cloneNode(_tDot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARuleExpr(this);
    }

    public PPredicate getPredicate()
    {
        return _predicate_;
    }

    public void setPredicate(PPredicate node)
    {
        if(_predicate_ != null)
        {
            _predicate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _predicate_ = node;
    }

    public TTImpliedby getTImpliedby()
    {
        return _tImpliedby_;
    }

    public void setTImpliedby(TTImpliedby node)
    {
        if(_tImpliedby_ != null)
        {
            _tImpliedby_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tImpliedby_ = node;
    }

    public PConjunction getConjunction()
    {
        return _conjunction_;
    }

    public void setConjunction(PConjunction node)
    {
        if(_conjunction_ != null)
        {
            _conjunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _conjunction_ = node;
    }

    public TTDot getTDot()
    {
        return _tDot_;
    }

    public void setTDot(TTDot node)
    {
        if(_tDot_ != null)
        {
            _tDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tDot_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_predicate_)
            + toString(_tImpliedby_)
            + toString(_conjunction_)
            + toString(_tDot_);
    }

    void removeChild(Node child)
    {
        if(_predicate_ == child)
        {
            _predicate_ = null;
            return;
        }

        if(_tImpliedby_ == child)
        {
            _tImpliedby_ = null;
            return;
        }

        if(_conjunction_ == child)
        {
            _conjunction_ = null;
            return;
        }

        if(_tDot_ == child)
        {
            _tDot_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_predicate_ == oldChild)
        {
            setPredicate((PPredicate) newChild);
            return;
        }

        if(_tImpliedby_ == oldChild)
        {
            setTImpliedby((TTImpliedby) newChild);
            return;
        }

        if(_conjunction_ == oldChild)
        {
            setConjunction((PConjunction) newChild);
            return;
        }

        if(_tDot_ == oldChild)
        {
            setTDot((TTDot) newChild);
            return;
        }

    }
}
