/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ATermlist extends PTermlist
{
    private PTermlist _termlist_;
    private TTComma _tComma_;
    private PTerm _term_;

    public ATermlist()
    {
    }

    public ATermlist(
        PTermlist _termlist_,
        TTComma _tComma_,
        PTerm _term_)
    {
        setTermlist(_termlist_);

        setTComma(_tComma_);

        setTerm(_term_);

    }
    public Object clone()
    {
        return new ATermlist(
            (PTermlist) cloneNode(_termlist_),
            (TTComma) cloneNode(_tComma_),
            (PTerm) cloneNode(_term_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermlist(this);
    }

    public PTermlist getTermlist()
    {
        return _termlist_;
    }

    public void setTermlist(PTermlist node)
    {
        if(_termlist_ != null)
        {
            _termlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _termlist_ = node;
    }

    public TTComma getTComma()
    {
        return _tComma_;
    }

    public void setTComma(TTComma node)
    {
        if(_tComma_ != null)
        {
            _tComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tComma_ = node;
    }

    public PTerm getTerm()
    {
        return _term_;
    }

    public void setTerm(PTerm node)
    {
        if(_term_ != null)
        {
            _term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _term_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_termlist_)
            + toString(_tComma_)
            + toString(_term_);
    }

    void removeChild(Node child)
    {
        if(_termlist_ == child)
        {
            _termlist_ = null;
            return;
        }

        if(_tComma_ == child)
        {
            _tComma_ = null;
            return;
        }

        if(_term_ == child)
        {
            _term_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_termlist_ == oldChild)
        {
            setTermlist((PTermlist) newChild);
            return;
        }

        if(_tComma_ == oldChild)
        {
            setTComma((TTComma) newChild);
            return;
        }

        if(_term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

    }
}
