/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ATerm extends PTerm
{
    private TTId _tId_;
    private PParamlist _paramlist_;

    public ATerm()
    {
    }

    public ATerm(
        TTId _tId_,
        PParamlist _paramlist_)
    {
        setTId(_tId_);

        setParamlist(_paramlist_);

    }
    public Object clone()
    {
        return new ATerm(
            (TTId) cloneNode(_tId_),
            (PParamlist) cloneNode(_paramlist_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATerm(this);
    }

    public TTId getTId()
    {
        return _tId_;
    }

    public void setTId(TTId node)
    {
        if(_tId_ != null)
        {
            _tId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tId_ = node;
    }

    public PParamlist getParamlist()
    {
        return _paramlist_;
    }

    public void setParamlist(PParamlist node)
    {
        if(_paramlist_ != null)
        {
            _paramlist_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _paramlist_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tId_)
            + toString(_paramlist_);
    }

    void removeChild(Node child)
    {
        if(_tId_ == child)
        {
            _tId_ = null;
            return;
        }

        if(_paramlist_ == child)
        {
            _paramlist_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tId_ == oldChild)
        {
            setTId((TTId) newChild);
            return;
        }

        if(_paramlist_ == oldChild)
        {
            setParamlist((PParamlist) newChild);
            return;
        }

    }
}
