/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class ATermTermlist extends PTermlist
{
    private PTerm _term_;

    public ATermTermlist()
    {
    }

    public ATermTermlist(
        PTerm _term_)
    {
        setTerm(_term_);

    }
    public Object clone()
    {
        return new ATermTermlist(
            (PTerm) cloneNode(_term_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermTermlist(this);
    }

    public PTerm getTerm()
    {
        return _term_;
    }

    public void setTerm(PTerm node)
    {
        if(_term_ != null)
        {
            _term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _term_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_term_);
    }

    void removeChild(Node child)
    {
        if(_term_ == child)
        {
            _term_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

    }
}
