/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import java.util.*;

import org.deri.iris.parser.analysis.*;

public final class AVarTerm extends PTerm
{
    private TTVariable _tVariable_;

    public AVarTerm()
    {
    }

    public AVarTerm(
        TTVariable _tVariable_)
    {
        setTVariable(_tVariable_);

    }
    public Object clone()
    {
        return new AVarTerm(
            (TTVariable) cloneNode(_tVariable_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarTerm(this);
    }

    public TTVariable getTVariable()
    {
        return _tVariable_;
    }

    public void setTVariable(TTVariable node)
    {
        if(_tVariable_ != null)
        {
            _tVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tVariable_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tVariable_);
    }

    void removeChild(Node child)
    {
        if(_tVariable_ == child)
        {
            _tVariable_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_tVariable_ == oldChild)
        {
            setTVariable((TTVariable) newChild);
            return;
        }

    }
}
