/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

public final class TTComma extends Token
{
    public TTComma()
    {
        super.setText(",");
    }

    public TTComma(int line, int pos)
    {
        super.setText(",");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTComma(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTComma(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTComma text.");
    }
}
