/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

public final class TTDot extends Token
{
    public TTDot()
    {
        super.setText(".");
    }

    public TTDot(int line, int pos)
    {
        super.setText(".");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTDot(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTDot(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTDot text.");
    }
}
