/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

public final class TTImpliedby extends Token
{
    public TTImpliedby()
    {
        super.setText(":-");
    }

    public TTImpliedby(int line, int pos)
    {
        super.setText(":-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTImpliedby(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTImpliedby(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTImpliedby text.");
    }
}
