/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

public final class TTQuery extends Token
{
    public TTQuery()
    {
        super.setText("?-");
    }

    public TTQuery(int line, int pos)
    {
        super.setText("?-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTQuery(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTQuery(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTQuery text.");
    }
}
