/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.node;

import org.deri.iris.parser.analysis.*;

public final class TTRpar extends Token
{
    public TTRpar()
    {
        super.setText(")");
    }

    public TTRpar(int line, int pos)
    {
        super.setText(")");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTRpar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTRpar(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTRpar text.");
    }
}
