/*
 * Integrated Rule Inference System (IRIS):
 * An extensible rule inference system for datalog with extensions by 
 * built-in predicates, default negation (under well-founded semantics), 
 * function symbols and contexts. 
 * 
 * Copyright (C) 2006  Digital Enterprise Research Institute (DERI), 
 * Leopold-Franzens-Universitaet Innsbruck, Technikerstrasse 21a, 
 * A-6020 Innsbruck. Austria.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
 * MA  02110-1301, USA.
 */
package org.deri.iris.basics;

import static org.deri.iris.factory.Factory.GRAPH;

import java.util.Arrays;
import java.util.List;

import org.deri.iris.api.basics.IAtom;
import org.deri.iris.api.basics.IBody;
import org.deri.iris.api.basics.IHead;
import org.deri.iris.api.basics.ILiteral;
import org.deri.iris.api.basics.IPredicate;
import org.deri.iris.api.basics.IQuery;
import org.deri.iris.api.basics.IRule;
import org.deri.iris.api.basics.ITuple;
import org.deri.iris.api.builtins.IBuiltInAtom;
import org.deri.iris.api.factory.IBasicFactory;
import org.deri.iris.api.terms.ITerm;

/**
 * @author Darko Anicic, DERI Innsbruck
 * @date 22.02.2006 16:03:34
 */

public class BasicFactory implements IBasicFactory {

	private static final IBasicFactory FACTORY = new BasicFactory();

	private BasicFactory() {
		// this is a singelton
	}

	public IAtom createAtom(IPredicate p) {
		return new Atom(p);
	}

	public IAtom createAtom(IPredicate p, ITerm... terms) {
		return createAtom(p, Arrays.asList(terms));
	}

	public IAtom createAtom(IPredicate p, List<ITerm> terms) {
		return new Atom(p, terms);
	}

	public IBody createBody(ILiteral... literals) {
		return createBody(Arrays.asList(literals));
	}

	public IBody createBody(List<ILiteral> literals) {
		return new Body(literals);
	}

	public IHead createHead(ILiteral... literals) {
		return createHead(Arrays.asList(literals));
	}

	public IHead createHead(List<ILiteral> literals) {
		return new Head(literals);
	}

	public ILiteral createLiteral(boolean isPositive, IAtom atom) {
		return new Literal(isPositive, atom);
	}

	public ILiteral createLiteral(boolean isPositive, IBuiltInAtom builtinAtom) {
		// TODO: autogenerated method block
		return null;
	}

	public ILiteral createLiteral(boolean isPositive, IPredicate predicate) {
		return createLiteral(isPositive, createAtom(predicate));
	}

	public ILiteral createLiteral(boolean positive, IPredicate p,
			ITerm... terms) {
		return createLiteral(positive, p, Arrays.asList(terms));
	}

	public ILiteral createLiteral(boolean positive, IPredicate p,
			List<ITerm> terms) {
		return createLiteral(positive, createAtom(p, terms));
	}

	public IPredicate createPredicate(String symbol, int arity) {
		return new Predicate(symbol, arity);
	}

	public IQuery createQuery(ILiteral... literals) {
		return new Query(createBody(literals));
	}

	public IQuery createQuery(List<ILiteral> literals) {
		return new Query(createBody(literals));
	}

	public IRule createRule(IHead head, IBody body) {
		IRule r =new Rule(head, body); 
		GRAPH.createPredicateGraph().addRule(r);
		return r;
	}

	public ITuple createTuple(ITerm... terms) {
		return createTuple(Arrays.asList(terms));
	}

	public ITuple createTuple(List<ITerm> terms) {
		return new Tuple(terms);
	}

	public static IBasicFactory getInstance() {
		return FACTORY;
	}

}
