/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.sti2.streamingiris.parser.node;

import at.sti2.streamingiris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTComma extends Token
{
    public TTComma(String text)
    {
        setText(text);
    }

    public TTComma(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTComma(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTComma(this);
    }
}
