/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.sti2.streamingiris.parser.node;

import at.sti2.streamingiris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTPreDatetime extends Token
{
    public TTPreDatetime()
    {
        super.setText("_datetime");
    }

    public TTPreDatetime(int line, int pos)
    {
        super.setText("_datetime");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPreDatetime(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPreDatetime(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPreDatetime text.");
    }
}
