/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.parser;

import org.deri.iris.parser.analysis.*;
import org.deri.iris.parser.lexer.*;
import org.deri.iris.parser.node.*;

import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected Node node;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    protected void filter() throws ParserException, LexerException, IOException
    {
    }

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int state, Node node, boolean filter) throws ParserException, LexerException, IOException
    {
        this.node = node;

        if(filter)
        {
            filter();
        }

        if(!stack.hasNext())
        {
            stack.add(new State(state, this.node));
            return;
        }

        State s = (State) stack.next();
        s.state = state;
        s.node = this.node;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private Node pop()
    {
        return (Node) ((State) stack.previous()).node;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, false);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
                    push(action[1], lexer.next(), true);
                    last_shift = action[1];
                    break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0: { Node node = new0(); push(goTo(0), node, true); } break;
                    case 1: { Node node = new1(); push(goTo(0), node, true); } break;
                    case 2: { Node node = new2(); push(goTo(8), node, false); } break;
                    case 3: { Node node = new3(); push(goTo(8), node, false); } break;
                    case 4: { Node node = new4(); push(goTo(1), node, true); } break;
                    case 5: { Node node = new5(); push(goTo(1), node, true); } break;
                    case 6: { Node node = new6(); push(goTo(1), node, true); } break;
                    case 7: { Node node = new7(); push(goTo(2), node, true); } break;
                    case 8: { Node node = new8(); push(goTo(2), node, true); } break;
                    case 9: { Node node = new9(); push(goTo(2), node, true); } break;
                    case 10: { Node node = new10(); push(goTo(3), node, true); } break;
                    case 11: { Node node = new11(); push(goTo(3), node, true); } break;
                    case 12: { Node node = new12(); push(goTo(4), node, true); } break;
                    case 13: { Node node = new13(); push(goTo(4), node, true); } break;
                    case 14: { Node node = new14(); push(goTo(5), node, true); } break;
                    case 15: { Node node = new15(); push(goTo(5), node, true); } break;
                    case 16: { Node node = new16(); push(goTo(6), node, true); } break;
                    case 17: { Node node = new17(); push(goTo(6), node, true); } break;
                    case 18: { Node node = new18(); push(goTo(7), node, true); } break;
                    case 19: { Node node = new19(); push(goTo(7), node, true); } break;
                    case 20: { Node node = new20(); push(goTo(7), node, true); } break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PProgram node1 = (PProgram) pop();
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }

    Node new0()
    {
        XPExpr node1 = null;
        AProgram node = new AProgram(node1);
        return node;
    }

    Node new1()
    {
        XPExpr node1 = (XPExpr) pop();
        AProgram node = new AProgram(node1);
        return node;
    }

    Node new2()
    {
        PExpr node2 = (PExpr) pop();
        XPExpr node1 = (XPExpr) pop();
        X1PExpr node = new X1PExpr(node1, node2);
        return node;
    }

    Node new3()
    {
        PExpr node1 = (PExpr) pop();
        X2PExpr node = new X2PExpr(node1);
        return node;
    }

    Node new4()
    {
        TTDot node4 = (TTDot) pop();
        PConjunction node3 = (PConjunction) pop();
        TTImpliedby node2 = (TTImpliedby) pop();
        PPredicate node1 = (PPredicate) pop();
        ARuleExpr node = new ARuleExpr(node1, node2, node3, node4);
        return node;
    }

    Node new5()
    {
        TTDot node2 = (TTDot) pop();
        PPredicate node1 = (PPredicate) pop();
        AFactExpr node = new AFactExpr(node1, node2);
        return node;
    }

    Node new6()
    {
        TTDot node3 = (TTDot) pop();
        PConjunction node2 = (PConjunction) pop();
        TTQuery node1 = (TTQuery) pop();
        AQueryExpr node = new AQueryExpr(node1, node2, node3);
        return node;
    }

    Node new7()
    {
        PBody node1 = (PBody) pop();
        ABodyConjunction node = new ABodyConjunction(node1);
        return node;
    }

    Node new8()
    {
        PBody node3 = (PBody) pop();
        TTAnd node2 = (TTAnd) pop();
        PConjunction node1 = (PConjunction) pop();
        AAndConjunction node = new AAndConjunction(node1, node2, node3);
        return node;
    }

    Node new9()
    {
        PBody node3 = (PBody) pop();
        TTComma node2 = (TTComma) pop();
        PConjunction node1 = (PConjunction) pop();
        ACommaConjunction node = new ACommaConjunction(node1, node2, node3);
        return node;
    }

    Node new10()
    {
        PPredicate node2 = (PPredicate) pop();
        TTNot node1 = (TTNot) pop();
        ANegatedBody node = new ANegatedBody(node1, node2);
        return node;
    }

    Node new11()
    {
        PPredicate node1 = (PPredicate) pop();
        ABody node = new ABody(node1);
        return node;
    }

    Node new12()
    {
        PParamlist node2 = null;
        TTId node1 = (TTId) pop();
        APredicate node = new APredicate(node1, node2);
        return node;
    }

    Node new13()
    {
        PParamlist node2 = (PParamlist) pop();
        TTId node1 = (TTId) pop();
        APredicate node = new APredicate(node1, node2);
        return node;
    }

    Node new14()
    {
        TTRpar node3 = (TTRpar) pop();
        PTermlist node2 = null;
        TTLpar node1 = (TTLpar) pop();
        AParamlist node = new AParamlist(node1, node2, node3);
        return node;
    }

    Node new15()
    {
        TTRpar node3 = (TTRpar) pop();
        PTermlist node2 = (PTermlist) pop();
        TTLpar node1 = (TTLpar) pop();
        AParamlist node = new AParamlist(node1, node2, node3);
        return node;
    }

    Node new16()
    {
        PTerm node1 = (PTerm) pop();
        ATermTermlist node = new ATermTermlist(node1);
        return node;
    }

    Node new17()
    {
        PTerm node3 = (PTerm) pop();
        TTComma node2 = (TTComma) pop();
        PTermlist node1 = (PTermlist) pop();
        ATermlist node = new ATermlist(node1, node2, node3);
        return node;
    }

    Node new18()
    {
        PParamlist node2 = null;
        TTId node1 = (TTId) pop();
        ATerm node = new ATerm(node1, node2);
        return node;
    }

    Node new19()
    {
        PParamlist node2 = (PParamlist) pop();
        TTId node1 = (TTId) pop();
        ATerm node = new ATerm(node1, node2);
        return node;
    }

    Node new20()
    {
        TTVariable node1 = (TTVariable) pop();
        AVarTerm node = new AVarTerm(node1);
        return node;
    }

    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {8, SHIFT, 1}, {9, SHIFT, 2}, },
			{{-1, ERROR, 1}, {3, SHIFT, 7}, {9, SHIFT, 2}, },
			{{-1, REDUCE, 12}, {5, SHIFT, 11}, },
			{{-1, ERROR, 3}, {10, ACCEPT, -1}, },
			{{-1, REDUCE, 3}, },
			{{-1, ERROR, 5}, {0, SHIFT, 13}, {1, SHIFT, 14}, },
			{{-1, REDUCE, 1}, {8, SHIFT, 1}, {9, SHIFT, 2}, },
			{{-1, ERROR, 7}, {9, SHIFT, 2}, },
			{{-1, ERROR, 8}, {0, SHIFT, 17}, {2, SHIFT, 18}, {4, SHIFT, 19}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 11}, {6, SHIFT, 20}, {7, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 14}, {3, SHIFT, 7}, {9, SHIFT, 2}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 18}, {3, SHIFT, 7}, {9, SHIFT, 2}, },
			{{-1, ERROR, 19}, {3, SHIFT, 7}, {9, SHIFT, 2}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 18}, {5, SHIFT, 11}, },
			{{-1, ERROR, 23}, {4, SHIFT, 29}, {6, SHIFT, 30}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 25}, {0, SHIFT, 31}, {2, SHIFT, 18}, {4, SHIFT, 19}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 29}, {7, SHIFT, 21}, {9, SHIFT, 22}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 17}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, },
			{{-1, 4}, {6, 15}, },
			{{-1, 8}, {14, 25}, },
			{{-1, 9}, {18, 26}, {19, 27}, },
			{{-1, 10}, {0, 5}, {6, 5}, {7, 16}, },
			{{-1, 12}, {22, 28}, },
			{{-1, 23}, },
			{{-1, 24}, {29, 32}, },
			{{-1, 6}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '?-', t id, EOF",
			"expecting: t not, t id",
			"expecting: '.', ':-', 'and', ',', '('",
			"expecting: EOF",
			"expecting: '.', ':-'",
			"expecting: t id",
			"expecting: '.', 'and', ','",
			"expecting: ')', t variable, t id",
			"expecting: '.', ':-', 'and', ','",
			"expecting: '.', ':-', 'and', ',', ')'",
			"expecting: ',', ')'",
			"expecting: ',', '(', ')'",
			"expecting: t variable, t id",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 0, 4, 0, 5, 6, 6, 6, 7, 8, 0, 1, 0, 6, 0, 1, 1, 9, 10, 11, 10, 10, 6, 6, 6, 10, 12, 9, 0, 10, 
        };*/
}
