/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.parser;

import org.deri.iris.parser.lexer.*;
import org.deri.iris.parser.node.*;
import org.deri.iris.parser.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AAprogram1Program */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AAprogram2Program */
		    {
			ArrayList list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce ARuleExpr */
		    {
			ArrayList list = new2();
			push(goTo(1), list, false);
		    }
		    break;
                    case 3: /* reduce AFactExpr */
		    {
			ArrayList list = new3();
			push(goTo(1), list, false);
		    }
		    break;
                    case 4: /* reduce AQueryExpr */
		    {
			ArrayList list = new4();
			push(goTo(1), list, false);
		    }
		    break;
                    case 5: /* reduce ARule */
		    {
			ArrayList list = new5();
			push(goTo(2), list, false);
		    }
		    break;
                    case 6: /* reduce AFact */
		    {
			ArrayList list = new6();
			push(goTo(3), list, false);
		    }
		    break;
                    case 7: /* reduce AQuery */
		    {
			ArrayList list = new7();
			push(goTo(4), list, false);
		    }
		    break;
                    case 8: /* reduce ABody */
		    {
			ArrayList list = new8();
			push(goTo(5), list, false);
		    }
		    break;
                    case 9: /* reduce AAndBody */
		    {
			ArrayList list = new9();
			push(goTo(5), list, false);
		    }
		    break;
                    case 10: /* reduce ACommaBody */
		    {
			ArrayList list = new10();
			push(goTo(5), list, false);
		    }
		    break;
                    case 11: /* reduce ANegatedLiteral */
		    {
			ArrayList list = new11();
			push(goTo(6), list, false);
		    }
		    break;
                    case 12: /* reduce ALiteral */
		    {
			ArrayList list = new12();
			push(goTo(6), list, false);
		    }
		    break;
                    case 13: /* reduce ABuiltinLiteral */
		    {
			ArrayList list = new13();
			push(goTo(6), list, false);
		    }
		    break;
                    case 14: /* reduce AApredicate1Predicate */
		    {
			ArrayList list = new14();
			push(goTo(7), list, false);
		    }
		    break;
                    case 15: /* reduce AApredicate2Predicate */
		    {
			ArrayList list = new15();
			push(goTo(7), list, false);
		    }
		    break;
                    case 16: /* reduce AAparamlist1Paramlist */
		    {
			ArrayList list = new16();
			push(goTo(8), list, false);
		    }
		    break;
                    case 17: /* reduce AAparamlist2Paramlist */
		    {
			ArrayList list = new17();
			push(goTo(8), list, false);
		    }
		    break;
                    case 18: /* reduce ATermTermlist */
		    {
			ArrayList list = new18();
			push(goTo(9), list, false);
		    }
		    break;
                    case 19: /* reduce ATermlist */
		    {
			ArrayList list = new19();
			push(goTo(9), list, false);
		    }
		    break;
                    case 20: /* reduce AFunctionTerm */
		    {
			ArrayList list = new20();
			push(goTo(10), list, false);
		    }
		    break;
                    case 21: /* reduce AVarTerm */
		    {
			ArrayList list = new21();
			push(goTo(10), list, false);
		    }
		    break;
                    case 22: /* reduce AConstantTerm */
		    {
			ArrayList list = new22();
			push(goTo(10), list, false);
		    }
		    break;
                    case 23: /* reduce ABuiltin */
		    {
			ArrayList list = new23();
			push(goTo(11), list, false);
		    }
		    break;
                    case 24: /* reduce AIdbuiltBuiltin */
		    {
			ArrayList list = new24();
			push(goTo(11), list, false);
		    }
		    break;
                    case 25: /* reduce ATerminal$Expr */
		    {
			ArrayList list = new25();
			push(goTo(12), list, true);
		    }
		    break;
                    case 26: /* reduce ANonTerminal$Expr */
		    {
			ArrayList list = new26();
			push(goTo(12), list, true);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AAprogram1Program */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        PProgram pprogramNode1;
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        }

        pprogramNode1 = new AProgram(listNode2);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AAprogram2Program */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pprogramNode1 = new AProgram(listNode3);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce ARuleExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PRule pruleNode2;
        pruleNode2 = (PRule)nodeArrayList1.get(0);

        pexprNode1 = new ARuleExpr(pruleNode2);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AFactExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PFact pfactNode2;
        pfactNode2 = (PFact)nodeArrayList1.get(0);

        pexprNode1 = new AFactExpr(pfactNode2);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce AQueryExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PQuery pqueryNode2;
        pqueryNode2 = (PQuery)nodeArrayList1.get(0);

        pexprNode1 = new AQueryExpr(pqueryNode2);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce ARule */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PRule pruleNode1;
        {
            // Block
        PPredicate ppredicateNode2;
        TTImpliedby ttimpliedbyNode3;
        PBody pbodyNode4;
        TTDot ttdotNode5;
        ppredicateNode2 = (PPredicate)nodeArrayList1.get(0);
        ttimpliedbyNode3 = (TTImpliedby)nodeArrayList2.get(0);
        pbodyNode4 = (PBody)nodeArrayList3.get(0);
        ttdotNode5 = (TTDot)nodeArrayList4.get(0);

        pruleNode1 = new ARule(ppredicateNode2, ttimpliedbyNode3, pbodyNode4, ttdotNode5);
        }
	nodeList.add(pruleNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AFact */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PFact pfactNode1;
        {
            // Block
        PPredicate ppredicateNode2;
        TTDot ttdotNode3;
        ppredicateNode2 = (PPredicate)nodeArrayList1.get(0);
        ttdotNode3 = (TTDot)nodeArrayList2.get(0);

        pfactNode1 = new AFact(ppredicateNode2, ttdotNode3);
        }
	nodeList.add(pfactNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AQuery */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        TTQuery ttqueryNode2;
        PBody pbodyNode3;
        TTDot ttdotNode4;
        ttqueryNode2 = (TTQuery)nodeArrayList1.get(0);
        pbodyNode3 = (PBody)nodeArrayList2.get(0);
        ttdotNode4 = (TTDot)nodeArrayList3.get(0);

        pqueryNode1 = new AQuery(ttqueryNode2, pbodyNode3, ttdotNode4);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce ABody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        PLiteral pliteralNode2;
        pliteralNode2 = (PLiteral)nodeArrayList1.get(0);

        pbodyNode1 = new ABody(pliteralNode2);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AAndBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        PBody pbodyNode2;
        TTAnd ttandNode3;
        PLiteral pliteralNode4;
        pbodyNode2 = (PBody)nodeArrayList1.get(0);
        ttandNode3 = (TTAnd)nodeArrayList2.get(0);
        pliteralNode4 = (PLiteral)nodeArrayList3.get(0);

        pbodyNode1 = new AAndBody(pbodyNode2, ttandNode3, pliteralNode4);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce ACommaBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        PBody pbodyNode2;
        TTComma ttcommaNode3;
        PLiteral pliteralNode4;
        pbodyNode2 = (PBody)nodeArrayList1.get(0);
        ttcommaNode3 = (TTComma)nodeArrayList2.get(0);
        pliteralNode4 = (PLiteral)nodeArrayList3.get(0);

        pbodyNode1 = new ACommaBody(pbodyNode2, ttcommaNode3, pliteralNode4);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce ANegatedLiteral */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiteral pliteralNode1;
        {
            // Block
        TTNot ttnotNode2;
        PPredicate ppredicateNode3;
        ttnotNode2 = (TTNot)nodeArrayList1.get(0);
        ppredicateNode3 = (PPredicate)nodeArrayList2.get(0);

        pliteralNode1 = new ANegatedLiteral(ttnotNode2, ppredicateNode3);
        }
	nodeList.add(pliteralNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce ALiteral */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiteral pliteralNode1;
        {
            // Block
        PPredicate ppredicateNode2;
        ppredicateNode2 = (PPredicate)nodeArrayList1.get(0);

        pliteralNode1 = new ALiteral(ppredicateNode2);
        }
	nodeList.add(pliteralNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce ABuiltinLiteral */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PLiteral pliteralNode1;
        {
            // Block
        PBuiltin pbuiltinNode2;
        pbuiltinNode2 = (PBuiltin)nodeArrayList1.get(0);

        pliteralNode1 = new ABuiltinLiteral(pbuiltinNode2);
        }
	nodeList.add(pliteralNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AApredicate1Predicate */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPredicate ppredicateNode1;
        {
            // Block
        TTId ttidNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        ttidNode2 = (TTId)nodeArrayList1.get(0);

        ppredicateNode1 = new APredicate(ttidNode2, null);
        }
	nodeList.add(ppredicateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AApredicate2Predicate */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PPredicate ppredicateNode1;
        {
            // Block
        TTId ttidNode2;
        PParamlist pparamlistNode3;
        ttidNode2 = (TTId)nodeArrayList1.get(0);
        pparamlistNode3 = (PParamlist)nodeArrayList2.get(0);

        ppredicateNode1 = new APredicate(ttidNode2, pparamlistNode3);
        }
	nodeList.add(ppredicateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AAparamlist1Paramlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PParamlist pparamlistNode1;
        {
            // Block
        TTLpar ttlparNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        TTRpar ttrparNode4;
        ttlparNode2 = (TTLpar)nodeArrayList1.get(0);
        ttrparNode4 = (TTRpar)nodeArrayList2.get(0);

        pparamlistNode1 = new AParamlist(ttlparNode2, null, ttrparNode4);
        }
	nodeList.add(pparamlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AAparamlist2Paramlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PParamlist pparamlistNode1;
        {
            // Block
        TTLpar ttlparNode2;
        PTermlist ptermlistNode3;
        TTRpar ttrparNode4;
        ttlparNode2 = (TTLpar)nodeArrayList1.get(0);
        ptermlistNode3 = (PTermlist)nodeArrayList2.get(0);
        ttrparNode4 = (TTRpar)nodeArrayList3.get(0);

        pparamlistNode1 = new AParamlist(ttlparNode2, ptermlistNode3, ttrparNode4);
        }
	nodeList.add(pparamlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce ATermTermlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTermlist ptermlistNode1;
        {
            // Block
        PTerm ptermNode2;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);

        ptermlistNode1 = new ATermTermlist(ptermNode2);
        }
	nodeList.add(ptermlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce ATermlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTermlist ptermlistNode1;
        {
            // Block
        PTermlist ptermlistNode2;
        TTComma ttcommaNode3;
        PTerm ptermNode4;
        ptermlistNode2 = (PTermlist)nodeArrayList1.get(0);
        ttcommaNode3 = (TTComma)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        ptermlistNode1 = new ATermlist(ptermlistNode2, ttcommaNode3, ptermNode4);
        }
	nodeList.add(ptermlistNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce AFunctionTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TTId ttidNode2;
        PParamlist pparamlistNode3;
        ttidNode2 = (TTId)nodeArrayList1.get(0);
        pparamlistNode3 = (PParamlist)nodeArrayList2.get(0);

        ptermNode1 = new AFunctionTerm(ttidNode2, pparamlistNode3);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AVarTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TTVariable ttvariableNode2;
        ttvariableNode2 = (TTVariable)nodeArrayList1.get(0);

        ptermNode1 = new AVarTerm(ttvariableNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce AConstantTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TTId ttidNode2;
        ttidNode2 = (TTId)nodeArrayList1.get(0);

        ptermNode1 = new AConstantTerm(ttidNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce ABuiltin */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBuiltin pbuiltinNode1;
        {
            // Block
        TTVariable ttvariableNode2;
        TTEq tteqNode3;
        TTVariable ttvariableNode4;
        ttvariableNode2 = (TTVariable)nodeArrayList1.get(0);
        tteqNode3 = (TTEq)nodeArrayList2.get(0);
        ttvariableNode4 = (TTVariable)nodeArrayList3.get(0);

        pbuiltinNode1 = new ABuiltin(ttvariableNode2, tteqNode3, ttvariableNode4);
        }
	nodeList.add(pbuiltinNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce AIdbuiltBuiltin */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBuiltin pbuiltinNode1;
        {
            // Block
        TTVariable ttvariableNode2;
        TTEq tteqNode3;
        TTId ttidNode4;
        ttvariableNode2 = (TTVariable)nodeArrayList1.get(0);
        tteqNode3 = (TTEq)nodeArrayList2.get(0);
        ttidNode4 = (TTId)nodeArrayList3.get(0);

        pbuiltinNode1 = new AIdbuiltBuiltin(ttvariableNode2, tteqNode3, ttidNode4);
        }
	nodeList.add(pbuiltinNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce ATerminal$Expr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PExpr pexprNode1;
        pexprNode1 = (PExpr)nodeArrayList1.get(0);
	if(pexprNode1 != null)
	{
	  listNode2.add(pexprNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce ANonTerminal$Expr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PExpr pexprNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pexprNode2 = (PExpr)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pexprNode2 != null)
	{
	  listNode3.add(pexprNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {8, SHIFT, 1}, {9, SHIFT, 2}, },
			{{-1, ERROR, 1}, {3, SHIFT, 10}, {7, SHIFT, 11}, {9, SHIFT, 2}, },
			{{-1, REDUCE, 14}, {5, SHIFT, 16}, },
			{{-1, ERROR, 3}, {12, ACCEPT, -1}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 8}, {0, SHIFT, 18}, {1, SHIFT, 19}, },
			{{-1, REDUCE, 1}, {8, SHIFT, 1}, {9, SHIFT, 2}, },
			{{-1, ERROR, 10}, {9, SHIFT, 2}, },
			{{-1, ERROR, 11}, {11, SHIFT, 22}, },
			{{-1, ERROR, 12}, {0, SHIFT, 23}, {2, SHIFT, 24}, {4, SHIFT, 25}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 16}, {6, SHIFT, 26}, {7, SHIFT, 27}, {9, SHIFT, 28}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 19}, {3, SHIFT, 10}, {7, SHIFT, 11}, {9, SHIFT, 2}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 22}, {7, SHIFT, 32}, {9, SHIFT, 33}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 24}, {3, SHIFT, 10}, {7, SHIFT, 11}, {9, SHIFT, 2}, },
			{{-1, ERROR, 25}, {3, SHIFT, 10}, {7, SHIFT, 11}, {9, SHIFT, 2}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 22}, {5, SHIFT, 16}, },
			{{-1, ERROR, 29}, {4, SHIFT, 37}, {6, SHIFT, 38}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 31}, {0, SHIFT, 39}, {2, SHIFT, 24}, {4, SHIFT, 25}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 37}, {7, SHIFT, 27}, {9, SHIFT, 28}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 19}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, },
			{{-1, 4}, {9, 20}, },
			{{-1, 5}, },
			{{-1, 6}, },
			{{-1, 7}, },
			{{-1, 12}, {19, 31}, },
			{{-1, 13}, {24, 34}, {25, 35}, },
			{{-1, 14}, {0, 8}, {9, 8}, {10, 21}, },
			{{-1, 17}, {28, 36}, },
			{{-1, 29}, },
			{{-1, 30}, {37, 40}, },
			{{-1, 15}, },
			{{-1, 9}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: '?-', t id, EOF",
			"expecting: t not, t variable, t id",
			"expecting: '.', ':-', 'and', ',', '('",
			"expecting: EOF",
			"expecting: '.', ':-'",
			"expecting: t id",
			"expecting: '='",
			"expecting: '.', 'and', ','",
			"expecting: ')', t variable, t id",
			"expecting: '.', ':-', 'and', ','",
			"expecting: t variable, t id",
			"expecting: '.', ':-', 'and', ',', ')'",
			"expecting: ',', ')'",
			"expecting: ',', '(', ')'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 0, 0, 0, 0, 4, 0, 5, 6, 7, 7, 7, 7, 8, 9, 0, 1, 0, 7, 10, 0, 1, 1, 11, 12, 13, 12, 12, 7, 7, 7, 7, 7, 12, 10, 11, 0, 12, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
