/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.parser;

import org.deri.iris.parser.analysis.*;
import org.deri.iris.parser.node.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTDot(TTDot node)
    {
        index = 0;
    }

    public void caseTTImpliedby(TTImpliedby node)
    {
        index = 1;
    }

    public void caseTTAnd(TTAnd node)
    {
        index = 2;
    }

    public void caseTTNot(TTNot node)
    {
        index = 3;
    }

    public void caseTTComma(TTComma node)
    {
        index = 4;
    }

    public void caseTTLpar(TTLpar node)
    {
        index = 5;
    }

    public void caseTTRpar(TTRpar node)
    {
        index = 6;
    }

    public void caseTTVariable(TTVariable node)
    {
        index = 7;
    }

    public void caseTTQuery(TTQuery node)
    {
        index = 8;
    }

    public void caseTTId(TTId node)
    {
        index = 9;
    }

    public void caseEOF(EOF node)
    {
        index = 10;
    }
}
