/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.parser;

import org.deri.iris.parser.node.*;
import org.deri.iris.parser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTTDot(@SuppressWarnings("unused") TTDot node)
    {
        this.index = 0;
    }

    @Override
    public void caseTTImpliedby(@SuppressWarnings("unused") TTImpliedby node)
    {
        this.index = 1;
    }

    @Override
    public void caseTTAnd(@SuppressWarnings("unused") TTAnd node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTNot(@SuppressWarnings("unused") TTNot node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTComma(@SuppressWarnings("unused") TTComma node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTLpar(@SuppressWarnings("unused") TTLpar node)
    {
        this.index = 5;
    }

    @Override
    public void caseTTRpar(@SuppressWarnings("unused") TTRpar node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTVariable(@SuppressWarnings("unused") TTVariable node)
    {
        this.index = 7;
    }

    @Override
    public void caseTTQuery(@SuppressWarnings("unused") TTQuery node)
    {
        this.index = 8;
    }

    @Override
    public void caseTTId(@SuppressWarnings("unused") TTId node)
    {
        this.index = 9;
    }

    @Override
    public void caseTTConst(@SuppressWarnings("unused") TTConst node)
    {
        this.index = 10;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 11;
    }
}
