/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.analysis;

import org.deri.iris.parser.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseARuleExpr(ARuleExpr node);
    void caseAFactExpr(AFactExpr node);
    void caseAQueryExpr(AQueryExpr node);
    void caseARule(ARule node);
    void caseAFact(AFact node);
    void caseAQuery(AQuery node);
    void caseABody(ABody node);
    void caseAAndBody(AAndBody node);
    void caseACommaBody(ACommaBody node);
    void caseANegatedLiteral(ANegatedLiteral node);
    void caseALiteral(ALiteral node);
    void caseAPredicate(APredicate node);
    void caseAParamlist(AParamlist node);
    void caseATermTermlist(ATermTermlist node);
    void caseATermlist(ATermlist node);
    void caseAFunctionTerm(AFunctionTerm node);
    void caseAVarTerm(AVarTerm node);
    void caseAConstantTerm(AConstantTerm node);

    void caseTTBlank(TTBlank node);
    void caseTTComment(TTComment node);
    void caseTTDot(TTDot node);
    void caseTTImpliedby(TTImpliedby node);
    void caseTTAnd(TTAnd node);
    void caseTTNot(TTNot node);
    void caseTTComma(TTComma node);
    void caseTTLpar(TTLpar node);
    void caseTTRpar(TTRpar node);
    void caseTTVariable(TTVariable node);
    void caseTTQuery(TTQuery node);
    void caseTTId(TTId node);
    void caseTTConst(TTConst node);
    void caseEOF(EOF node);
}
