/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.analysis;

import java.util.*;
import org.deri.iris.parser.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseAProgram(AProgram node)
    {
        defaultCase(node);
    }

    public void caseARuleExpr(ARuleExpr node)
    {
        defaultCase(node);
    }

    public void caseAFactExpr(AFactExpr node)
    {
        defaultCase(node);
    }

    public void caseAQueryExpr(AQueryExpr node)
    {
        defaultCase(node);
    }

    public void caseARule(ARule node)
    {
        defaultCase(node);
    }

    public void caseAFact(AFact node)
    {
        defaultCase(node);
    }

    public void caseAQuery(AQuery node)
    {
        defaultCase(node);
    }

    public void caseABody(ABody node)
    {
        defaultCase(node);
    }

    public void caseAAndBody(AAndBody node)
    {
        defaultCase(node);
    }

    public void caseACommaBody(ACommaBody node)
    {
        defaultCase(node);
    }

    public void caseANegatedLiteral(ANegatedLiteral node)
    {
        defaultCase(node);
    }

    public void caseALiteral(ALiteral node)
    {
        defaultCase(node);
    }

    public void caseABuiltinLiteral(ABuiltinLiteral node)
    {
        defaultCase(node);
    }

    public void caseAPredicate(APredicate node)
    {
        defaultCase(node);
    }

    public void caseAParamlist(AParamlist node)
    {
        defaultCase(node);
    }

    public void caseATermTermlist(ATermTermlist node)
    {
        defaultCase(node);
    }

    public void caseATermlist(ATermlist node)
    {
        defaultCase(node);
    }

    public void caseAFunctionTerm(AFunctionTerm node)
    {
        defaultCase(node);
    }

    public void caseAVarTerm(AVarTerm node)
    {
        defaultCase(node);
    }

    public void caseAConstantTerm(AConstantTerm node)
    {
        defaultCase(node);
    }

    public void caseABuiltin(ABuiltin node)
    {
        defaultCase(node);
    }

    public void caseAIdbuiltBuiltin(AIdbuiltBuiltin node)
    {
        defaultCase(node);
    }

    public void caseTTBlank(TTBlank node)
    {
        defaultCase(node);
    }

    public void caseTTComment(TTComment node)
    {
        defaultCase(node);
    }

    public void caseTTDot(TTDot node)
    {
        defaultCase(node);
    }

    public void caseTTImpliedby(TTImpliedby node)
    {
        defaultCase(node);
    }

    public void caseTTAnd(TTAnd node)
    {
        defaultCase(node);
    }

    public void caseTTNot(TTNot node)
    {
        defaultCase(node);
    }

    public void caseTTComma(TTComma node)
    {
        defaultCase(node);
    }

    public void caseTTLpar(TTLpar node)
    {
        defaultCase(node);
    }

    public void caseTTRpar(TTRpar node)
    {
        defaultCase(node);
    }

    public void caseTTVariable(TTVariable node)
    {
        defaultCase(node);
    }

    public void caseTTQuery(TTQuery node)
    {
        defaultCase(node);
    }

    public void caseTTId(TTId node)
    {
        defaultCase(node);
    }

    public void caseTTConst(TTConst node)
    {
        defaultCase(node);
    }

    public void caseTTEq(TTEq node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
