/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.iris.parser.analysis;

import java.util.*;
import org.deri.iris.parser.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        {
            List<PExpr> copy = new ArrayList<PExpr>(node.getExpr());
            Collections.reverse(copy);
            for(PExpr e : copy)
            {
                e.apply(this);
            }
        }
        outAProgram(node);
    }

    public void inARuleExpr(ARuleExpr node)
    {
        defaultIn(node);
    }

    public void outARuleExpr(ARuleExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARuleExpr(ARuleExpr node)
    {
        inARuleExpr(node);
        if(node.getRule() != null)
        {
            node.getRule().apply(this);
        }
        outARuleExpr(node);
    }

    public void inAFactExpr(AFactExpr node)
    {
        defaultIn(node);
    }

    public void outAFactExpr(AFactExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFactExpr(AFactExpr node)
    {
        inAFactExpr(node);
        if(node.getFact() != null)
        {
            node.getFact().apply(this);
        }
        outAFactExpr(node);
    }

    public void inAQueryExpr(AQueryExpr node)
    {
        defaultIn(node);
    }

    public void outAQueryExpr(AQueryExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAQueryExpr(AQueryExpr node)
    {
        inAQueryExpr(node);
        if(node.getQuery() != null)
        {
            node.getQuery().apply(this);
        }
        outAQueryExpr(node);
    }

    public void inARule(ARule node)
    {
        defaultIn(node);
    }

    public void outARule(ARule node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARule(ARule node)
    {
        inARule(node);
        if(node.getTDot() != null)
        {
            node.getTDot().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getTImpliedby() != null)
        {
            node.getTImpliedby().apply(this);
        }
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        outARule(node);
    }

    public void inAFact(AFact node)
    {
        defaultIn(node);
    }

    public void outAFact(AFact node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFact(AFact node)
    {
        inAFact(node);
        if(node.getTDot() != null)
        {
            node.getTDot().apply(this);
        }
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        outAFact(node);
    }

    public void inAQuery(AQuery node)
    {
        defaultIn(node);
    }

    public void outAQuery(AQuery node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAQuery(AQuery node)
    {
        inAQuery(node);
        if(node.getTDot() != null)
        {
            node.getTDot().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        if(node.getTQuery() != null)
        {
            node.getTQuery().apply(this);
        }
        outAQuery(node);
    }

    public void inABody(ABody node)
    {
        defaultIn(node);
    }

    public void outABody(ABody node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABody(ABody node)
    {
        inABody(node);
        if(node.getLiteral() != null)
        {
            node.getLiteral().apply(this);
        }
        outABody(node);
    }

    public void inAAndBody(AAndBody node)
    {
        defaultIn(node);
    }

    public void outAAndBody(AAndBody node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndBody(AAndBody node)
    {
        inAAndBody(node);
        if(node.getLiteral() != null)
        {
            node.getLiteral().apply(this);
        }
        if(node.getTAnd() != null)
        {
            node.getTAnd().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        outAAndBody(node);
    }

    public void inACommaBody(ACommaBody node)
    {
        defaultIn(node);
    }

    public void outACommaBody(ACommaBody node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACommaBody(ACommaBody node)
    {
        inACommaBody(node);
        if(node.getLiteral() != null)
        {
            node.getLiteral().apply(this);
        }
        if(node.getTComma() != null)
        {
            node.getTComma().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        outACommaBody(node);
    }

    public void inANegatedLiteral(ANegatedLiteral node)
    {
        defaultIn(node);
    }

    public void outANegatedLiteral(ANegatedLiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegatedLiteral(ANegatedLiteral node)
    {
        inANegatedLiteral(node);
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        if(node.getTNot() != null)
        {
            node.getTNot().apply(this);
        }
        outANegatedLiteral(node);
    }

    public void inALiteral(ALiteral node)
    {
        defaultIn(node);
    }

    public void outALiteral(ALiteral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALiteral(ALiteral node)
    {
        inALiteral(node);
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        outALiteral(node);
    }

    public void inAPredicate(APredicate node)
    {
        defaultIn(node);
    }

    public void outAPredicate(APredicate node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPredicate(APredicate node)
    {
        inAPredicate(node);
        if(node.getParamlist() != null)
        {
            node.getParamlist().apply(this);
        }
        if(node.getTId() != null)
        {
            node.getTId().apply(this);
        }
        outAPredicate(node);
    }

    public void inAParamlist(AParamlist node)
    {
        defaultIn(node);
    }

    public void outAParamlist(AParamlist node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParamlist(AParamlist node)
    {
        inAParamlist(node);
        if(node.getTRpar() != null)
        {
            node.getTRpar().apply(this);
        }
        if(node.getTermlist() != null)
        {
            node.getTermlist().apply(this);
        }
        if(node.getTLpar() != null)
        {
            node.getTLpar().apply(this);
        }
        outAParamlist(node);
    }

    public void inATermTermlist(ATermTermlist node)
    {
        defaultIn(node);
    }

    public void outATermTermlist(ATermTermlist node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermTermlist(ATermTermlist node)
    {
        inATermTermlist(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermTermlist(node);
    }

    public void inATermlist(ATermlist node)
    {
        defaultIn(node);
    }

    public void outATermlist(ATermlist node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermlist(ATermlist node)
    {
        inATermlist(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getTComma() != null)
        {
            node.getTComma().apply(this);
        }
        if(node.getTermlist() != null)
        {
            node.getTermlist().apply(this);
        }
        outATermlist(node);
    }

    public void inAFunctionTerm(AFunctionTerm node)
    {
        defaultIn(node);
    }

    public void outAFunctionTerm(AFunctionTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFunctionTerm(AFunctionTerm node)
    {
        inAFunctionTerm(node);
        if(node.getParamlist() != null)
        {
            node.getParamlist().apply(this);
        }
        if(node.getTId() != null)
        {
            node.getTId().apply(this);
        }
        outAFunctionTerm(node);
    }

    public void inAVarTerm(AVarTerm node)
    {
        defaultIn(node);
    }

    public void outAVarTerm(AVarTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarTerm(AVarTerm node)
    {
        inAVarTerm(node);
        if(node.getTVariable() != null)
        {
            node.getTVariable().apply(this);
        }
        outAVarTerm(node);
    }

    public void inAConstantTerm(AConstantTerm node)
    {
        defaultIn(node);
    }

    public void outAConstantTerm(AConstantTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstantTerm(AConstantTerm node)
    {
        inAConstantTerm(node);
        if(node.getTId() != null)
        {
            node.getTId().apply(this);
        }
        outAConstantTerm(node);
    }
}
