/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.sti2.streamingiris.parser.node;

import at.sti2.streamingiris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTPreDuration extends Token
{
    public TTPreDuration()
    {
        super.setText("_duration");
    }

    public TTPreDuration(int line, int pos)
    {
        super.setText("_duration");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPreDuration(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPreDuration(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPreDuration text.");
    }
}
