/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.sti2.streamingiris.parser.node;

import at.sti2.streamingiris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTRpar extends Token
{
    public TTRpar()
    {
        super.setText(")");
    }

    public TTRpar(int line, int pos)
    {
        super.setText(")");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTRpar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTRpar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTRpar text.");
    }
}
