/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.mins.parser.analysis;

import java.util.*;
import org.deri.mins.parser.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable in;
    private Hashtable out;

    public Object getIn(Node node)
    {
        if(in == null)
        {
            return null;
        }

        return in.get(node);
    }

    public void setIn(Node node, Object in)
    {
        if(this.in == null)
        {
            this.in = new Hashtable(1);
        }

        if(in != null)
        {
            this.in.put(node, in);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(out == null)
        {
            return null;
        }

        return out.get(node);
    }

    public void setOut(Node node, Object out)
    {
        if(this.out == null)
        {
            this.out = new Hashtable(1);
        }

        if(out != null)
        {
            this.out.put(node, out);
        }
        else
        {
            this.out.remove(node);
        }
    }
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseAProgram(AProgram node)
    {
        defaultCase(node);
    }

    public void caseARuleExpr(ARuleExpr node)
    {
        defaultCase(node);
    }

    public void caseAFactExpr(AFactExpr node)
    {
        defaultCase(node);
    }

    public void caseAQueryExpr(AQueryExpr node)
    {
        defaultCase(node);
    }

    public void caseABodyConjunction(ABodyConjunction node)
    {
        defaultCase(node);
    }

    public void caseAAndConjunction(AAndConjunction node)
    {
        defaultCase(node);
    }

    public void caseACommaConjunction(ACommaConjunction node)
    {
        defaultCase(node);
    }

    public void caseANegatedBody(ANegatedBody node)
    {
        defaultCase(node);
    }

    public void caseABody(ABody node)
    {
        defaultCase(node);
    }

    public void caseAPredicate(APredicate node)
    {
        defaultCase(node);
    }

    public void caseAParamlist(AParamlist node)
    {
        defaultCase(node);
    }

    public void caseATermTermlist(ATermTermlist node)
    {
        defaultCase(node);
    }

    public void caseATermlist(ATermlist node)
    {
        defaultCase(node);
    }

    public void caseATerm(ATerm node)
    {
        defaultCase(node);
    }

    public void caseAVarTerm(AVarTerm node)
    {
        defaultCase(node);
    }

    public void caseTTBlank(TTBlank node)
    {
        defaultCase(node);
    }

    public void caseTTComment(TTComment node)
    {
        defaultCase(node);
    }

    public void caseTTDot(TTDot node)
    {
        defaultCase(node);
    }

    public void caseTTImpliedby(TTImpliedby node)
    {
        defaultCase(node);
    }

    public void caseTTAnd(TTAnd node)
    {
        defaultCase(node);
    }

    public void caseTTNot(TTNot node)
    {
        defaultCase(node);
    }

    public void caseTTComma(TTComma node)
    {
        defaultCase(node);
    }

    public void caseTTLpar(TTLpar node)
    {
        defaultCase(node);
    }

    public void caseTTRpar(TTRpar node)
    {
        defaultCase(node);
    }

    public void caseTTVariable(TTVariable node)
    {
        defaultCase(node);
    }

    public void caseTTQuery(TTQuery node)
    {
        defaultCase(node);
    }

    public void caseTTId(TTId node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(Node node)
    {
    }
}
