/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.mins.parser.analysis;

import org.deri.mins.parser.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseARuleExpr(ARuleExpr node);
    void caseAFactExpr(AFactExpr node);
    void caseAQueryExpr(AQueryExpr node);
    void caseABodyConjunction(ABodyConjunction node);
    void caseAAndConjunction(AAndConjunction node);
    void caseACommaConjunction(ACommaConjunction node);
    void caseANegatedBody(ANegatedBody node);
    void caseABody(ABody node);
    void caseAPredicate(APredicate node);
    void caseAParamlist(AParamlist node);
    void caseATermTermlist(ATermTermlist node);
    void caseATermlist(ATermlist node);
    void caseATerm(ATerm node);
    void caseAVarTerm(AVarTerm node);

    void caseTTBlank(TTBlank node);
    void caseTTComment(TTComment node);
    void caseTTDot(TTDot node);
    void caseTTImpliedby(TTImpliedby node);
    void caseTTAnd(TTAnd node);
    void caseTTNot(TTNot node);
    void caseTTComma(TTComma node);
    void caseTTLpar(TTLpar node);
    void caseTTRpar(TTRpar node);
    void caseTTVariable(TTVariable node);
    void caseTTQuery(TTQuery node);
    void caseTTId(TTId node);
    void caseEOF(EOF node);
}
