/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.deri.mins.parser.analysis;

import java.util.*;
import org.deri.mins.parser.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(Node node)
    {
    }

    public void defaultOut(Node node)
    {
    }

    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgram().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        {
            Object temp[] = node.getExpr().toArray();
            for(int i = 0; i < temp.length; i++)
            {
                ((PExpr) temp[i]).apply(this);
            }
        }
        outAProgram(node);
    }

    public void inARuleExpr(ARuleExpr node)
    {
        defaultIn(node);
    }

    public void outARuleExpr(ARuleExpr node)
    {
        defaultOut(node);
    }

    public void caseARuleExpr(ARuleExpr node)
    {
        inARuleExpr(node);
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        if(node.getTImpliedby() != null)
        {
            node.getTImpliedby().apply(this);
        }
        if(node.getConjunction() != null)
        {
            node.getConjunction().apply(this);
        }
        if(node.getTDot() != null)
        {
            node.getTDot().apply(this);
        }
        outARuleExpr(node);
    }

    public void inAFactExpr(AFactExpr node)
    {
        defaultIn(node);
    }

    public void outAFactExpr(AFactExpr node)
    {
        defaultOut(node);
    }

    public void caseAFactExpr(AFactExpr node)
    {
        inAFactExpr(node);
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        if(node.getTDot() != null)
        {
            node.getTDot().apply(this);
        }
        outAFactExpr(node);
    }

    public void inAQueryExpr(AQueryExpr node)
    {
        defaultIn(node);
    }

    public void outAQueryExpr(AQueryExpr node)
    {
        defaultOut(node);
    }

    public void caseAQueryExpr(AQueryExpr node)
    {
        inAQueryExpr(node);
        if(node.getTQuery() != null)
        {
            node.getTQuery().apply(this);
        }
        if(node.getConjunction() != null)
        {
            node.getConjunction().apply(this);
        }
        if(node.getTDot() != null)
        {
            node.getTDot().apply(this);
        }
        outAQueryExpr(node);
    }

    public void inABodyConjunction(ABodyConjunction node)
    {
        defaultIn(node);
    }

    public void outABodyConjunction(ABodyConjunction node)
    {
        defaultOut(node);
    }

    public void caseABodyConjunction(ABodyConjunction node)
    {
        inABodyConjunction(node);
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        outABodyConjunction(node);
    }

    public void inAAndConjunction(AAndConjunction node)
    {
        defaultIn(node);
    }

    public void outAAndConjunction(AAndConjunction node)
    {
        defaultOut(node);
    }

    public void caseAAndConjunction(AAndConjunction node)
    {
        inAAndConjunction(node);
        if(node.getConjunction() != null)
        {
            node.getConjunction().apply(this);
        }
        if(node.getTAnd() != null)
        {
            node.getTAnd().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        outAAndConjunction(node);
    }

    public void inACommaConjunction(ACommaConjunction node)
    {
        defaultIn(node);
    }

    public void outACommaConjunction(ACommaConjunction node)
    {
        defaultOut(node);
    }

    public void caseACommaConjunction(ACommaConjunction node)
    {
        inACommaConjunction(node);
        if(node.getConjunction() != null)
        {
            node.getConjunction().apply(this);
        }
        if(node.getTComma() != null)
        {
            node.getTComma().apply(this);
        }
        if(node.getBody() != null)
        {
            node.getBody().apply(this);
        }
        outACommaConjunction(node);
    }

    public void inANegatedBody(ANegatedBody node)
    {
        defaultIn(node);
    }

    public void outANegatedBody(ANegatedBody node)
    {
        defaultOut(node);
    }

    public void caseANegatedBody(ANegatedBody node)
    {
        inANegatedBody(node);
        if(node.getTNot() != null)
        {
            node.getTNot().apply(this);
        }
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        outANegatedBody(node);
    }

    public void inABody(ABody node)
    {
        defaultIn(node);
    }

    public void outABody(ABody node)
    {
        defaultOut(node);
    }

    public void caseABody(ABody node)
    {
        inABody(node);
        if(node.getPredicate() != null)
        {
            node.getPredicate().apply(this);
        }
        outABody(node);
    }

    public void inAPredicate(APredicate node)
    {
        defaultIn(node);
    }

    public void outAPredicate(APredicate node)
    {
        defaultOut(node);
    }

    public void caseAPredicate(APredicate node)
    {
        inAPredicate(node);
        if(node.getTId() != null)
        {
            node.getTId().apply(this);
        }
        if(node.getParamlist() != null)
        {
            node.getParamlist().apply(this);
        }
        outAPredicate(node);
    }

    public void inAParamlist(AParamlist node)
    {
        defaultIn(node);
    }

    public void outAParamlist(AParamlist node)
    {
        defaultOut(node);
    }

    public void caseAParamlist(AParamlist node)
    {
        inAParamlist(node);
        if(node.getTLpar() != null)
        {
            node.getTLpar().apply(this);
        }
        if(node.getTermlist() != null)
        {
            node.getTermlist().apply(this);
        }
        if(node.getTRpar() != null)
        {
            node.getTRpar().apply(this);
        }
        outAParamlist(node);
    }

    public void inATermTermlist(ATermTermlist node)
    {
        defaultIn(node);
    }

    public void outATermTermlist(ATermTermlist node)
    {
        defaultOut(node);
    }

    public void caseATermTermlist(ATermTermlist node)
    {
        inATermTermlist(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermTermlist(node);
    }

    public void inATermlist(ATermlist node)
    {
        defaultIn(node);
    }

    public void outATermlist(ATermlist node)
    {
        defaultOut(node);
    }

    public void caseATermlist(ATermlist node)
    {
        inATermlist(node);
        if(node.getTermlist() != null)
        {
            node.getTermlist().apply(this);
        }
        if(node.getTComma() != null)
        {
            node.getTComma().apply(this);
        }
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermlist(node);
    }

    public void inATerm(ATerm node)
    {
        defaultIn(node);
    }

    public void outATerm(ATerm node)
    {
        defaultOut(node);
    }

    public void caseATerm(ATerm node)
    {
        inATerm(node);
        if(node.getTId() != null)
        {
            node.getTId().apply(this);
        }
        if(node.getParamlist() != null)
        {
            node.getParamlist().apply(this);
        }
        outATerm(node);
    }

    public void inAVarTerm(AVarTerm node)
    {
        defaultIn(node);
    }

    public void outAVarTerm(AVarTerm node)
    {
        defaultOut(node);
    }

    public void caseAVarTerm(AVarTerm node)
    {
        inAVarTerm(node);
        if(node.getTVariable() != null)
        {
            node.getTVariable().apply(this);
        }
        outAVarTerm(node);
    }
}
