/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.sti2.streamingiris.parser.node;

import at.sti2.streamingiris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTImpliedby extends Token
{
    public TTImpliedby()
    {
        super.setText(":-");
    }

    public TTImpliedby(int line, int pos)
    {
        super.setText(":-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTImpliedby(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTImpliedby(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTImpliedby text.");
    }
}
