/* This file was generated by SableCC (http://www.sablecc.org/). */

package at.sti2.streamingiris.parser.node;

import at.sti2.streamingiris.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTPreGday extends Token
{
    public TTPreGday()
    {
        super.setText("_gday");
    }

    public TTPreGday(int line, int pos)
    {
        super.setText("_gday");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTPreGday(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTPreGday(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTPreGday text.");
    }
}
